/*
 * CAN_header.h
 *
 * Created: 11/15/2017 4:03:50 PM
 *  Author: dinos
 */ 


#ifndef CAN_HEADER_H_
#define CAN_HEADER_H_

//ID[10..8]
#define CAN_NODE_1_ID 0x100
#define CAN_NODE_2_ID 0x200

//ID[7..4]
#define CAN_GRP_MULTIBOARD_ID 0x10
#define CAN_GRP_DATA_ID 0x20

//ID[3..0]
	//Multiboard
#define CAN_MODULE_JOYSTICK_ID 0x1
#define CAN_MODULE_SLIDER_ID 0x2
#define CAN_MODULE_BUTTON_ID 0x3
	//State
#define CAN_MODULE_STATE_ID 0x1
#define CAN_MODULE_SCORE_ID 0x2
#define CAN_MODULE_ACTUATOR_ID 0x3



//ID									(	Node			|	GROUP					|	MODULE					)
#define CAN_JOYSTICK_ID					(	CAN_NODE_1_ID	|	CAN_GRP_MULTIBOARD_ID	|	CAN_MODULE_JOYSTICK_ID	)
#define CAN_SLIDER_ID					(	CAN_NODE_1_ID	|	CAN_GRP_MULTIBOARD_ID	|	CAN_MODULE_SLIDER_ID	)
#define CAN_BUTTON_ID					(	CAN_NODE_1_ID	|	CAN_GRP_MULTIBOARD_ID	|	CAN_MODULE_BUTTON_ID	)
#define CAN_STATE_FROMNODE1_ID			(	CAN_NODE_1_ID	|	CAN_GRP_DATA_ID			|	CAN_MODULE_STATE_ID		)
#define CAN_STATE_FROMNODE2_ID			(	CAN_NODE_2_ID	|	CAN_GRP_DATA_ID			|	CAN_MODULE_STATE_ID		)
#define CAN_SCORE_FROMNODE1_ID			(	CAN_NODE_1_ID	|	CAN_GRP_DATA_ID			|	CAN_MODULE_SCORE_ID		)
#define CAN_SCORE_FROMNODE2_ID			(	CAN_NODE_2_ID	|	CAN_GRP_DATA_ID			|	CAN_MODULE_SCORE_ID		)
#define CAN_ACTUATOR_FROMNODE1_ID		(	CAN_NODE_1_ID	|	CAN_GRP_DATA_ID			|	CAN_MODULE_ACTUATOR_ID	)
#define CAN_ACTUATOR_FROMNODE2_ID		(	CAN_NODE_2_ID	|	CAN_GRP_DATA_ID			|	CAN_MODULE_ACTUATOR_ID	)




#endif /* CAN_HEADER_H_ */